name: "Dúvida · Question"
description: "Uma pergunta sobre como usar · A question about using Rapdex"
title: "[dúvida] "
labels: ["dúvida"]
body:
  - type: textarea
    id: pergunta
    attributes:
      label: Sua pergunta · Your question
    validations:
      required: true
